name: g3py
dependencies:
  - pip
  - python=3.7
  - pip:
    - pysimconnect
    - fastapi
    - fastapi_utils
    - sse-starlette
    - aiohttp
    - aiohttp_sse_client
    - httpx
    - uvicorn
    - aiofiles
    - ruamel.yaml
    - pytest
    - pytest-asyncio
    - pytest-xprocess
    - flake8
    - flake8-black
    - mypy

