name: g3py
dependencies:
  - pip
  - python=3.7
  - pip:
    - pysimconnect
    - fastapi
    - fastapi_utils
    - uvicorn
    - aiofiles
    - ruamel.yaml
    - flake8
    - flake8-black
    - mypy

